<a href="https://colab.research.google.com/github/RudravMahure/Pandas/blob/main/pandas_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**PANDAS **

Welcome to the lesson on Pandas.Pandas is a package for data manipulation and analysis in Python. The name Pandas is derived from the econometrics term Panel Data. Pandas incorporates two additional data structures into Python, namely Pandas Series and Pandas DataFrame. These data structures allow us to work with labeled and relational data in an easy and intuitive manner. These lessons are intended as a basic overview of Pandas and introduces some of its most important features.

**Why Use Pandas?**

The recent success of machine learning algorithms is partly due to the huge amounts of data that we have available to train our algorithms on. However, when it comes to data, quantity is not the only thing that matters, the quality of your data is just as important.

More often than not, large datasets will often have missing values, outliers, incorrect values, etc… Having data with a lot of missing or bad values, for example, is not going to allow your machine learning algorithms to perform well.

his is where Pandas come in. Pandas Series and DataFrames are designed for fast data analysis and manipulation, as well as being flexible and easy to use. Below are just a few features that makes Pandas an excellent package for data analysis:

Allows the use of labels for rows and columns
Can calculate rolling statistics on time series data
Easy handling of NaN values
Is able to load data of different formats into DataFrames
Can join and merge different datasets together
It integrates with NumPy and Matplotlib
For these and other reasons, Pandas DataFrames have become one of the most commonly used Pandas object for data analysis in Python.

**PANDAS SERIES:**

A Pandas series is a one-dimensional array-like object that can hold many data types, such as numbers or strings. One of the main differences between Pandas Series and NumPy ndarrays is that you can assign an index label to each element in the Pandas Series. In other words, you can name the indices of your Pandas Series anything you want. Another big difference between Pandas Series and NumPy ndarrays is that Pandas Series can hold data of different data types.

In [3]:
import pandas as pd
print(pd.show_versions())

/usr/local/lib/python3.10/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")



INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.109+
Version          : #1 SMP Fri Jun 9 10:57:30 UTC 2023
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : 0.29.36
pytest           : 7.4.0
hypothesis       : None
sphinx           : 5.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.7
jinja2           : 3.1.2
IPython          : 7.34.0
pandas_datareader: 0.10.0
bs4              : 4.11.2
bottleneck       : None
brotli       

In [ ]:
#Creating Pandas series

items=pd.Series(index=['red','blue','green'],data=[10,21,37])
print(items)
print(items['red'])

red      10
blue     21
green    37
dtype: int64
10


**Attributes of Panda Series:**

Let's see some of the attributes of the pandas series that helps us to understand our series

In [ ]:
items.shape   # gives us the  sizes of each dimension of the data
items.ndim   # gives us the number of dimensions of the data
items.size   # gives us the total number of items in the array
items.index   # gives us the list indeices of the series
items.values   #gives us the data of the series

array([1, 2, 3])

If you are dealing with a very large Pandas Series and if you are not sure whether an index label exists, you can check by using the in command

In [ ]:
#Checking is index is present in the dataset
x='red' in items
y='yellow' in items

print('Is red index present in items:-',x)
print('is yellow index present in items:-',y)

Is red index present in items:- True
is yellow index present in items:- False


**Accessing and Deleting Elements in Pandas Series:**

Now let's look at how we can access or modify elements in a Pandas Series. One great advantage of Pandas Series is that it allows us to access data in many different ways. Elements can be accessed using index labels or numerical indices inside square brackets, [ ], similar to how we access elements in NumPy ndarrays. Since we can use numerical indices, we can use both positive and negative integers to access data from the beginning or from the end of the Series, respectively.

In [ ]:
items['red'] #getting elements from series just like dictionary

1

In [ ]:
items[['red','blue']]  #gives list of elememts with there indices

red     1
blue    2
dtype: int64

In [ ]:
items[0] #gives first element

1

In [ ]:
items[-1] #gives last element

3

In [ ]:
items[[0,1]] #gives list of elements with there indices

red     1
blue    2
dtype: int64

In order to remove any ambiguity from whether we are reffering to the labeled index or the numerical index, panda series have two attributes loc and iloc.

>The attribute loc stands for the location and is used to explicitly state that we are using our labeled index.

>The attribute iloc stands for integer location and is used to explicitly state that we are using a numerical index

In [ ]:
items

red      10
blue     21
green    37
dtype: int64

In [ ]:
items.loc[['red','blue']] #gives items according to index(which can be anything)

red     10
blue    21
dtype: int64

In [ ]:
items.iloc[[0,1]] #gives items according to numerical index

red     10
blue    21
dtype: int64

Pandas Series are also mutable like NumPy ndarrays, which means we can change the elements of a Pandas Series after it has been created.

In [ ]:
items['red']='colour' #change elements in series
items['yellow']=76    #add elements in series
items

red       colour
blue          21
green         37
yellow        76
dtype: object

We can see that our series is now modified


**Deleting values from Pandas Series:**


We can also delete items from a Pandas Series by using the .drop() method. The Series.drop(label) method removes the given label from the given Series.

In [ ]:

items.drop('red') #drop elements temparary

blue      21
green     37
yellow    76
dtype: object

As we see the chocolate item is no longer is present in the series returned by the method.

Note: However, this drops elements from the series out of place meaning the code above just returned the modified series and actually didn't change the actual series.

In [ ]:
items

red       colour
blue          21
green         37
yellow        76
dtype: object

If you want to modify the actual series, we can use either of the two methods

overwrite the returned series on the original one

item = item.drop('red')

use inplace agrgument and set it to True

item.drop('red', inplace=True)

Let's try the second one :p

In [ ]:
items['red']='colour'

In [ ]:
items.drop('red',inplace=True) #permanently delete elements from series
items

blue      21
green     37
yellow    76
dtype: object

**Arithmatic operations on Pandas Series:**

Just like with NumPy ndarrays, we can perform element-wise arithmetic operations on Pandas Series. We will look at the arithematic operations between pandas series and single numbers.
Let's first make a new series

In [ ]:
sweets = pd.Series(data=[10, 5, 7], index=['candies', 'donuts', 'ladoos'])
sweets

candies    10
donuts      5
ladoos      7
dtype: int64

We can now modify the data in sweets by performing basic arithmetic operations. Let's see some examples

In [ ]:
sweets+2

candies    12
donuts      7
ladoos      9
dtype: int64

In [ ]:
sweets-2

candies    8
donuts     3
ladoos     5
dtype: int64

In [ ]:
sweets*2

candies    20
donuts     10
ladoos     14
dtype: int64

In [ ]:
sweets/2

candies    5.0
donuts     2.5
ladoos     3.5
dtype: float64

In [ ]:
arr=pd.Series(index=['red','blue','green'],data=[25,16,9])
arr

red      25
blue     16
green     9
dtype: int64

In [ ]:
# WE CAN ALSO APPLY MATHEMATICAL FUNCTIONS FROM NUMPY SUCH AS SQAURE ROOT
import numpy as np
np.sqrt(arr) #gives square of number

red      5.0
blue     4.0
green    3.0
dtype: float64

Pandas also allows us to only apply arithmetic operations on selected items in our arr list. Let's see some examples

In [ ]:
np.power(arr,2) #power the data with given index in this example 2 is the power

red      625
blue     256
green     81
dtype: int64

In [ ]:
np.exp(arr)

red      7.200490e+10
blue     8.886111e+06
green    8.103084e+03
dtype: float64

We can also apply arithemeatic operations on specific elements

In [ ]:
arr['red']-3

22

In [ ]:
arr[['red','blue']]*3

red     75
blue    48
dtype: int64

Note: We can also apply arithematic operations on a pandas series of mixed data types, provided the operations are defines on all the datatypes.

Let's use the item series we made earlier

In [ ]:
item = pd.Series(data=[15, 5, 'No'], index=['chocolates', 'chips', 'milk'])
item

chocolates    15
chips          5
milk          No
dtype: object

In [ ]:
item * 5  #SINCE MULTIPLICATION OPERATION IS DEFINED FOR BOTH STRINGS AND INTEGERS, THE CODE DOESN'T RETURN ANY ERROR

chocolates            75
chips                 25
milk          NoNoNoNoNo
dtype: object

In [ ]:
item/2 #SINCE THE DIVISION OPERATION IS DEFINED ONLY FOR NUMBERS AND NOT FOR STRING, THE CODE WILL RETURN AN ERROR

TypeError: ignored

In [ ]:
item+4 #SINCE THE ADDITION OPERATION IS DEFINED ONLY FOR NUMBERS AND NOT FOR STRING, THE CODE WILL RETURN AN ERROR

TypeError: ignored

In [ ]:
item-4  #SINCE THE SUBTRACTION OPERATION IS DEFINED ONLY FOR NUMBERS AND NOT FOR STRING, THE CODE WILL RETURN AN ERROR

TypeError: ignored

**2. PANDAS DATAFRAME**

Dataframe is a two dimensional object which holds rows and columns and can hold values of different data types.


   We can create a dataframe manually or by loading data from a file.

Let's first ceate a dataframe manually:

  First let's create a dictionary of pandas series and pass it into pandas dataframe

In [ ]:
items={'Rudrav':pd.Series([20,113,21,50],index=['watch','pants','books','toys']),
       'Pooja':pd.Series([27,23,180],index=['watch','t-shirt','books'])}

# item is a dictionary for two people containing some items and the cost of the item

In [ ]:
#WE CAN CREATE A DATA FRAME BY PASSINF THE DICTIONARY TO THE DataFrame FUNCTION
cart=pd.DataFrame(items)
cart

Rudrav  Pooja
books      21.0  180.0
pants     113.0    NaN
t-shirt     NaN   23.0
toys       50.0    NaN
watch      20.0   27.0

In [ ]:
pd.DataFrame(items)

Rudrav  Pooja
books      21.0  180.0
pants     113.0    NaN
t-shirt     NaN   23.0
toys       50.0    NaN
watch      20.0   27.0

Make sure to capitalize the D and F while calling the dataframe function.

The dataframe is displayed in the tabular form
The row labels for the dataframe are built from the union of the index labels we provided in the series and the column labels for the dataframe is taken from the keys of the dictionaries.

The dataframe has NaN values because for Rudrav we have no item like t-shirt and pants in the dicrionary we provided and similarly we have NaN values for column Pooja.

In [ ]:
# IN ABOVE EXAMPLE WE PROVIDED THE DICTIONARIES THAT CLEARLY DEFINED THE INDEX LABLES, HOWEVER IF WE DON'T PROVIDE THE INDEX LABELS,
# THEN THE DATAFRAME WOULD USE THE NUMERICAL INDEX VALUES
# LET'S CREATE THE SAME DICIONARY WITHOUT THE INDEXED LABELS
new_item = {'Pooja': pd.Series([250, 15, 70, 100]),
        'Rudarv': pd.Series([120, 50, 90])}



# NOW MAKE THE DATAFRAME USING THE NEW DICTIONARIES
df = pd.DataFrame(new_item)
df

Pooja  Rudarv
0    250   120.0
1     15    50.0
2     70    90.0
3    100     NaN

In [ ]:
print(np.array(df))

[[250. 120.]
 [ 15.  50.]
 [ 70.  90.]
 [100.  nan]]


The dataframe uses the numerical indices.


**2.a Attributes :**

Like we did in pandas series, we can also extract information from pandas dataframe using some attributes.

In [ ]:
cart.index

Index(['books', 'pants', 't-shirt', 'toys', 'watch'], dtype='object')

In [ ]:
cart.columns

Index(['Rudrav', 'Pooja'], dtype='object')

In [ ]:
cart.values

array([[ 21., 180.],
       [113.,  nan],
       [ nan,  23.],
       [ 50.,  nan],
       [ 20.,  27.]])

In [ ]:
cart.values


array([[ 21., 180.],
       [113.,  nan],
       [ nan,  23.],
       [ 50.,  nan],
       [ 20.,  27.]])

In [ ]:
cart.values

array([[ 21., 180.],
       [113.,  nan],
       [ nan,  23.],
       [ 50.,  nan],
       [ 20.,  27.]])

In [ ]:
cart.size

10

**NOTE:**

While creating the cart dataframe, we passed the whole dictionary to the dataframe function. However, there might be cases when we are only interested in some specific subset of the whole data. Pandas let's us select which data we want to put into the DataFrame, with the keywords columns and index.

In [ ]:
print(items)
rudrav_cart=pd.DataFrame(items,columns=['rudarv'])
rudrav_cart

{'Rudrav': watch     20
pants    113
books     21
toys      50
dtype: int64, 'Pooja': watch       27
t-shirt     23
books      180
dtype: int64}


Empty DataFrame
Columns: [rudarv]
Index: []

In [ ]:
selected_item = pd.DataFrame(items, index=['pants', 'toys'])
selected_item

Rudrav  Pooja
pants     113    NaN
toys       50    NaN

In [ ]:
rudrav_selected_item = pd.DataFrame(items, columns=['rudarv'], index=['pant', 'books'])
rudrav_selected_item

rudarv
pant     NaN
books    NaN

We can also create a dataframe from a dictionary of lists or arrays. The procedure is same as before, we start by creating the dictionary and then pass it into the dataframe function. In this case however all the list or arrays in the dictionary must be of the same length.

In [4]:
data={'Integer':[1,2,3],
      'Float':[1.2,4.3,5.6]}

df=pd.DataFrame(data)
df

Integer  Float
0        1    1.2
1        2    4.3
2        3    5.6

In [6]:
#Creating a dataframe using dictionry of python
new_data=[{'Apple':20,'Banana':15,'Orange':5},{'Apple':15,'Orange':25,'Banana':30,'Graphes':35}]

df=pd.DataFrame(new_data,index=['Shop1','Shop2'])
df

Apple  Banana  Orange  Graphes
Shop1     20      15       5      NaN
Shop2     15      30      25     35.0

DataFrame used the numerical row indices. If we want to assign the row indices some values, we can use:

In [8]:
df.index=['A',"B"]
df

Apple  Banana  Orange  Graphes
A     20      15       5      NaN
B     15      30      25     35.0

Accessing the values in a DataFrame

In [9]:
df[["Apple"]]

Apple
A     20
B     15

In [10]:
df['Apple']

A    20
B    15
Name: Apple, dtype: int64

In [11]:
df.loc["A"]

Apple      20.0
Banana     15.0
Orange      5.0
Graphes     NaN
Name: A, dtype: float64

In [12]:
df['Apple']['A']  ##accessing a specific value

20

In [18]:
## IF WE WANT TO ADD A NEW COLUMN TO OUR DATAFRAME,  WE CAN ADD LIKE THIS:

df['corn'] = [5, 7]
df

df['mango']=[5,'five']
df

Apple  Banana  Orange  Graphes  corn mango
A     20      15       5      NaN     5     5
B     15      30      25     35.0     7  five

In [19]:
new_person = [{'apple':15, 'banana': 17, 'corn': 3, 'orange':5}]
new_df = pd.DataFrame(new_person, index=['C'])
new_df


apple  banana  corn  orange
C     15      17     3       5

In [20]:
## WE CAN NOW ADD THE NEW ROW TO THE ORIGINAL DATAFRAME

df = df.append(new_df)
df

<ipython-input-20-a81c798dc323>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_df)


Apple  Banana  Orange  Graphes  corn mango  apple  banana  orange
A   20.0    15.0     5.0      NaN     5     5    NaN     NaN     NaN
B   15.0    30.0    25.0     35.0     7  five    NaN     NaN     NaN
C    NaN     NaN     NaN      NaN     3   NaN   15.0    17.0     5.0

It is also possible to insert columns in the DataFrame using insert method to any location we want. The insert method allows us to specify:


the location,
label, and
the data
of the column that we want to add.

In [21]:
df.insert(5,'ginger',[7,11,13])
df.insert(5, 'potato', 7)
# THE FIRST ARGUMENT IS LOCATION OF THE COLUMN
# THE SECOND ARGUMENT IS THE LABEL FOR THE COLUMN
# AND THE LAST ONE IS THE DATA FOR THE COLUMN
df

Apple  Banana  Orange  Graphes  corn  potato  ginger mango  apple  banana  \
A   20.0    15.0     5.0      NaN     5       7       7     5    NaN     NaN   
B   15.0    30.0    25.0     35.0     7       7      11  five    NaN     NaN   
C    NaN     NaN     NaN      NaN     3       7      13   NaN   15.0    17.0   

   orange  
A     NaN  
B     NaN  
C     5.0

We can also delete the columns and rows using two methods:

pop
drop

NOTE: The pop method allows us to delete columns while the drop method allows us to delete both rows and columns by using the access keyword.

In [22]:
df.pop('ginger')      #columns deletion only
df

Apple  Banana  Orange  Graphes  corn  potato mango  apple  banana  orange
A   20.0    15.0     5.0      NaN     5       7     5    NaN     NaN     NaN
B   15.0    30.0    25.0     35.0     7       7  five    NaN     NaN     NaN
C    NaN     NaN     NaN      NaN     3       7   NaN   15.0    17.0     5.0

In [24]:
df = df.drop(['Graphes', 'Orange'], axis=1)   # AXIS = 1 MEANS WE ARE REMOVING COLUMNS
df

Apple  Banana  corn  potato mango  apple  banana  orange
A   20.0    15.0     5       7     5    NaN     NaN     NaN
B   15.0    30.0     7       7  five    NaN     NaN     NaN
C    NaN     NaN     3       7   NaN   15.0    17.0     5.0

In [25]:
df = df.drop(['B', 'C'], axis=0)   # AXIS = 0 MEANS WE ARE REMOVING ROWS
df

Apple  Banana  corn  potato mango  apple  banana  orange
A   20.0    15.0     5       7     5    NaN     NaN     NaN

To change the name of any row or any column, we use the rename method

In [27]:
df  = df.rename(columns={'Banana':'pineapple'})
df

df=df.rename(columns={'Apple':'apple','orange':'Orange'})
df

apple  pineapple  corn  potato strawberry  apple  pineapple  Orange
A   20.0       15.0     5       7          5    NaN        NaN     NaN

Now let's change the name of the row

In [28]:
df  = df.rename(index={'A':'personA'})
df

apple  pineapple  corn  potato strawberry  apple  pineapple  Orange
personA   20.0       15.0     5       7          5    NaN        NaN     NaN